//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DB_Auto_Backup.DataSource.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackupTask()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public string DbName { get; set; }
        public bool UseCredentials { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public System.TimeSpan StartsAt { get; set; }
        public int MaxBackupFilesCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
