//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DB_Auto_Backup.DataSource.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid Id { get; set; }
        public int BackupTaskId { get; set; }
        public bool IsError { get; set; }
        public string Message { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
    
        public virtual BackupTask BackupTask { get; set; }
    }
}
